In [1]:
import numpy as np

### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [46]:
# function to Sort the matrix. 
def get_sorted_matrix(matrix): 
    return np.sort(matrix)


# Sort this matrix based on values in 2nd column.
def sorted_based_column(matrix):
    sorted_indices = np.argsort(matrix[ : , 1])
    sorted_matrix = matrix[sorted_indices]
    return sorted_matrix

# Sort this matrix based on max value in each row. 
def sort_based_max(matrix): 

    max_element = np.max(matrix, axis=1)
    sorted_indices = np.argsort(max_element)
    return matrix[sorted_indices]

#  Sort based on elements value. 
def sort_based_value(matrix): 

    flat_array = matrix.flatten()
    sorted_array = np.sort(flat_array).reshape(3, 4)
    return sorted_array


In [11]:
matrix = np.random.randint(0, 100, 12).reshape(3, 4)
print(matrix)

[[20 14 99 78]
 [31 75 61 30]
 [55 43 93 18]]


In [47]:
sorted_matrix = get_sorted_matrix(matrix)
sorted_based_colunm = sorted_based_column(matrix)
sorted_based_max = sort_based_max(matrix)
sorted_based_val = sort_based_value(matrix)
print(sorted_based_val)

[[14 18 20 30]
 [31 43 55 61]
 [75 78 93 99]]


### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

In [113]:
def add_subject_marks(marks): 
    new_marks = np.array([85, 80, 90, 75, 90]).reshape(marks.shape[0], 1)
    return np.append(marks, new_marks, axis = 1)

def add_two_student(marks): 
    new_marks = np.arange(80, 90).reshape(2, marks.shape[1])
    return np.append(marks, new_marks, axis = 0)

def add_total_sum_col(marks): 

    rowwise_sum = np.sum(marks, axis = 1).reshape(marks.shape[0], 1)
    # print(rowwise_sum)
    return np.append(marks, rowwise_sum, axis = 1)

# Sort the array(non-ascending order) 
def sort_array(marks): 
    # print(np.argsort(marks[ : , len(new_marks[0])])) 
    reverse_indices = np.argsort(marks[ : , len(new_marks[0])])[ : : -1] 
    # print(reverse_indices)

    return marks[reverse_indices[[0, 1]]]

In [116]:
marks = np.array([
                    [90, 91, 92, 93], 
                    [80, 81, 72, 63], 
                    [60, 94, 91, 53], 
                    [50, 61, 99, 84], 
                    [90, 91, 92, 90]
                ])

new_marks = add_subject_marks(marks)
print(new_marks)
print('**')
new_marks = add_two_student(new_marks)
print(new_marks)
print('**')
total_marks = add_total_sum_col(new_marks)
print(new_marks)
print('**')
top_two_row = sort_array(total_marks)
print(top_two_row)

[[90 91 92 93 85]
 [80 81 72 63 80]
 [60 94 91 53 90]
 [50 61 99 84 75]
 [90 91 92 90 90]]
**
[[90 91 92 93 85]
 [80 81 72 63 80]
 [60 94 91 53 90]
 [50 61 99 84 75]
 [90 91 92 90 90]
 [80 81 82 83 84]
 [85 86 87 88 89]]
**
[[90 91 92 93 85]
 [80 81 72 63 80]
 [60 94 91 53 90]
 [50 61 99 84 75]
 [90 91 92 90 90]
 [80 81 82 83 84]
 [85 86 87 88 89]]
**
[[ 90  91  92  90  90 453]
 [ 90  91  92  93  85 451]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]

```

In [130]:
def row_wise_unique(arr):
    return np.unique(arr, axis=0) 

def col_wise_unique(arr):
    return np.unique(arr, axis=1)
    

In [137]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]]) 

print('Row-wise : \n', row_wise_unique(arr))
print()
print('Column-wise : \n', col_wise_unique(arr))

Row-wise : 
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Column-wise : 
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [145]:
arr = np.array([
                    [90, 91, 92, 93], 
                    [80, 81, 72, 63], 
                    [60, 94, 91, 53], 
                    [50, 61, 99, 84], 
                    [90, 91, 92, 90]
                ])


# it will do the flip on both the axis at the same time.
np.flip(arr)


array([[90, 92, 91, 90],
       [84, 99, 61, 50],
       [53, 91, 94, 60],
       [63, 72, 81, 80],
       [93, 92, 91, 90]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6

```

In [40]:
def get_max_row(arr, threshold): 
    
    mask_array = np.any(arr > threshold, axis=1)
    resulted_rows = np.where(mask_array == True)
    # print(resulted_rows)
    print(arr[np.any(arr > threshold, axis=1)])
    return resulted_rows

In [41]:
arr = np.array([  [1,2,3,4,5], 
                  [10,-3,30,4,5], 
                  [3,2,5,-4,5], 
                  [9,7,3,6,5]
               ])

threshold = 6
print(get_max_row(arr, threshold))

[[10 -3 30  4  5]
 [ 9  7  3  6  5]]
(array([1, 3]),)


### `Q-6:` How to convert an array of arrays into a flat 1d array ?

In [51]:
def get_flat_array(arr): 
    return arr.flatten()

In [54]:
# 2D array
arr = np.array([  [1,2,3,4,5], 
                  [10,-3,30,4,5], 
                  [3,2,5,-4,5], 
                  [9,7,3,6,5]
               ])
# 3D array 
threeD_arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

get_flat_array(threeD_arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

```

In [104]:
import numpy as np 

def remove_max_min(arr): 
    
    max_element_idx = np.argmax(arr)
    min_element_idx = np.argmin(arr)
    # print(max_element_idx, min_element_idx)
    print(arr.shape)
    return np.delete(arr, [min_element_idx, max_element_idx]).reshape(arr.shape[0], arr.shape[1] - 2)

In [105]:
# seed function fix the values it will be same on every execution. 
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape(1, 200)
resulted_array = remove_max_min(arr)
# print(resulted_array) 
print(resulted_array.shape)

(1, 200)
(1, 198)


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [130]:
def limit_values(arr): 

    limit_value_array = np.clip(arr, min=100, max=200)
    # print(limit_value_array)

    sorted_array = np.sort(limit_value_array)
    # print(sorted_array) 

    cum_sum_array = np.cumsum(sorted_array)

    return cum_sum_array

In [131]:
np.random.seed(42)
arr = np.random.randint(100, 701, 20)

resulted_array = limit_values(arr)
print(resulted_array)

[ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [176]:
def compare_values(arr): 
    
    rounded_values = np.round(arr, 3)

    zero_percentile = np.percentile(rounded_values, 0)
    hundred_percentile = np.percentile(rounded_values, 100)
    # print(zero_percentile, hundred_percentile)
    if zero_percentile == np.min(arr):
        print('Zero percentile is equal to min values')
    else:
        print('Zero percentile is not equal to min values')

    if hundred_percentile == np.max(arr):
        print('Hundred percentile is equal to min values')
    else:
        print('Hundred percentile is not equal to min values')

    diff = np.percentile(rounded_values, 51) - np.percentile(rounded_values, 50)
    print('Difference between 51th percenile and 50th percentile values : ', diff)

In [177]:
arr = np.random.random(20)
# print(arr)
compare_values(arr)

Zero percentile is not equal to min values
Hundred percentile is not equal to min values
Difference between 51th percenile and 50th percentile values :  0.00019000000000002348
