## Numpy Fundamentals.

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays.

In [1]:
import numpy as np 

#### 1. First is np.array() function.

In [6]:
# 1D array. 
a1 = np.array([1, 2, 3, 4])
a1

array([1, 2, 3, 4])

In [7]:
# 2D numpy array also called Matrix.
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 3D numpy array also called tensor. 
a3 = np.array(
    [
        [[1, 2], [4, 5]], 
        [[6, 7], [8, 9]]
    ]
)
a3

array([[[1, 2],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

#### 2. Using dtype.

In [17]:
a1 = np.array([1, 2, 3], dtype = float)
a2 = np.array([4, 5, 6], dtype = int)
a3 = np.array([9, 8, 7], dtype = complex)
a4 = np.array([9, 0, 6], dtype = bool)

print(a1)
print(a2) 
print(a3)
print(a4)

[1. 2. 3.]
[4 5 6]
[9.+0.j 8.+0.j 7.+0.j]
[ True False  True]


#### 3. np.arange() function to make a 1D array.

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# when we are doing reshape, multiplicaation of the numbers always equals total numbers of element.
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.arange(16).reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

#### 4. np.ones() function, and np.zeros() function. 

In [31]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 5. np.random.random() function, and np.linspace() function. 

In [36]:
# it will generate the number between 0 and 1. 
np.random.random((3, 2))

array([[0.61763745, 0.79377729],
       [0.50884124, 0.3664995 ],
       [0.50002532, 0.90525303]])

In [42]:
# np.linspace(startingPoint, endPoint, difference)
np.linspace(10, 90, 9)

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

#### 6. np.identity() function to generate the identity matrix.

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Array Attributes. 
- As we know array is the object of numpy class, so it has a authority to access attributes of numpy class.

In [48]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(27).reshape(3, 3, 3)

In [51]:
print(a1)
print('*' * 50)
print(a2)
print('*' * 50)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
**************************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [54]:
# ndim --> tell the dimension of the array. 
print(a1.ndim) 
print(a2.ndim)
print(a3.ndim)

1
2
3


In [55]:
# shape --> tell the shape of the array. 
print(a1.shape) 
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(3, 3, 3)


In [58]:
# size --> tell the number of element in the array. 
print(a1.size)
print(a2.size)
print(a3.size)

10
12
27


In [60]:
# itemsize  -> tell the size of the each item
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [62]:
# dtype. 
print(a1.dtype)
print(a2.dtype) 
print(a3.dtype) 

int32
int64
int64


### Changing datatype.

In [64]:
# astype. 
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

### Array Operations. 

In [67]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [69]:
print(a1)
print('*' * 50)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [79]:
# Scaler Operation. 

In [80]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [81]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [82]:
2 + a1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [83]:
a1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [84]:
# Vector Operation. 

In [85]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [86]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [87]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [88]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [89]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [91]:
# relational operation. 
print(a1)

a1 >= 5

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

### Array Functions.

In [110]:
a1 = np.arange(1, 15, 2)
a2 = np.arange(12, 24).reshape(3, 4)
a3 = np.arange(27).reshape(3, 3, 3)
a1

array([ 1,  3,  5,  7,  9, 11, 13])

##### max/min/sum/prod

In [111]:
# max function. 
print(np.max(a1))
# axis = 0 means column, and axis = 1 means row. 
print(np.max(a2, axis=0))

print(np.max(a2, axis = 1))

13
[20 21 22 23]
[15 19 23]


In [112]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [114]:
# min function. 
print(np.min(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.min(a2, axis=0))

print(np.min(a2, axis = 1))

12
[12 13 14 15]
[12 16 20]


In [121]:
# sum function
print(np.sum(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.sum(a2, axis=0))

print(np.sum(a2, axis = 1))

210
[48 51 54 57]
[54 70 86]


In [122]:
# prod function
print(np.prod(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.prod(a2, axis=0))

print(np.prod(a2, axis = 1))

647647525324800
[3840 4641 5544 6555]
[ 32760  93024 212520]


##### mean/median/std/var

In [123]:
a1 = np.arange(1, 15, 2)
a2 = np.arange(12, 24).reshape(3, 4)
a3 = np.arange(27).reshape(3, 3, 3)

In [125]:
# mean function. 
print(np.mean(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.mean(a2, axis=0))

print(np.mean(a2, axis = 1))

17.5
[16. 17. 18. 19.]
[13.5 17.5 21.5]


In [126]:
# median function. 
print(np.median(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.median(a2, axis=0))

print(np.median(a2, axis = 1))

17.5
[16. 17. 18. 19.]
[13.5 17.5 21.5]


In [127]:
# standarrd deviation.
print(np.std(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.std(a2, axis=0))

print(np.std(a2, axis = 1))

3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


In [129]:
# variance function 
print(np.var(a2))

# axis = 0 means column, and axis = 1 means row. 
print(np.var(a2, axis=0))

print(np.var(a2, axis = 1))

11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


In [135]:
# trigonomoetric functions. 
print(np.sin(a1))
print('**' * 68)

print(np.cos(a1))
print('**' * 68)

print(np.tan(a1))
print('**' * 68)

[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849 -0.99999021
  0.42016704]
****************************************************************************************************************************************
[ 0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026  0.0044257
  0.90744678]
****************************************************************************************************************************************
[ 1.55740772e+00 -1.42546543e-01 -3.38051501e+00  8.71447983e-01
 -4.52315659e-01 -2.25950846e+02  4.63021133e-01]
****************************************************************************************************************************************


#### dot product(Almost similar to the matrix multiplication). 

In [141]:
a1 = np.arange(12).reshape(4, 3)
a2 = np.arange(12).reshape(3, 4)

In [143]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [144]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
np.dot(a1, a2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [149]:
# round/floor/ceil 
a1 = np.random.random((2, 3)) * 100
a1

array([[90.95364667, 93.79784915, 28.49474545],
       [63.81322722, 31.9763168 , 19.63695337]])

In [148]:
np.round(a1)

array([[43., 97., 47.],
       [49., 34., 40.]])

In [150]:
np.floor(a1)

array([[90., 93., 28.],
       [63., 31., 19.]])

In [151]:
np.ceil(a1)

array([[91., 94., 29.],
       [64., 32., 20.]])

### Indexing and Slicing.

In [152]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [153]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### Indexing

In [157]:
print(a2[1,0])

4


In [158]:
# access the element of the 3D array. 
print(a3[1,0,1])

5


#### Slicing

In [162]:
a1[2:5:2]

array([2, 4])

In [160]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [161]:
a2[1,::3]

array([4, 7])

In [163]:
a2[0,:]

array([0, 1, 2, 3])

In [164]:
a2[:,2]

array([ 2,  6, 10])

In [165]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [166]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [167]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [168]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [169]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [173]:
# 1D array. 
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [174]:
# iterating over the 2D array. 
a2 = np.arange(12).reshape(4, 3)
for i in a2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [175]:
# iterating over the 3D array. 
a2 = np.arange(27).reshape(3, 3, 3)
for i in a2:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [177]:
# accessing the one by one element from 2D or 3D array.
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [179]:
# reshape function
a1 = np.arange(12).reshape(3, 4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
# transpose of a matrix. 
print(a1)
np.transpose(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [182]:
# ravel
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [185]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [186]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [187]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [191]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
# horizontal splitting
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [195]:
# vertical splitting
np.vsplit(a1, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]