**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [3]:
import numpy as np
a1 = np.zeros(10, dtype = int)
a1[4] = 1
print(a1)

[0 0 0 0 1 0 0 0 0 0]


### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
a = int(input('Enter first number : '))
b = int(input('Enter second number : '))

a1 = np.random.random((a, b))

print(a1)

Enter first number :  4
Enter second number :  5


[[0.45319757 0.37050186 0.09400767 0.11625541 0.29698231]
 [0.78369596 0.31600062 0.52347124 0.77276598 0.084488  ]
 [0.29548411 0.82094247 0.13927967 0.97948726 0.03598981]
 [0.85560966 0.65293716 0.40087969 0.50865064 0.38940258]]


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [19]:
def create_array(a, b):

    result = np.ones(b, dtype=int)
    for i in range(1, a):
        if i == a - 1: 
            a1 = np.ones(b, dtype=int)
            result = np.vstack((result, a1)) 
        else:
            a1 = np.zeros(b, dtype=int) 
            a1[0] = 1
            a1[b - 1] = 1
            result = np.vstack((result, a1)) 
            
    return result
            


a = int(input('Enter first number : '))
b = int(input('Enter second number : ')) 

result = create_array(a, b)
print(result)

Enter first number :  5
Enter second number :  3


[[1 1 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [22]:
import numpy as np 

a1 = np.random.random(10)
print(a1)

[0.18357592 0.65327874 0.70997622 0.60029015 0.8597387  0.54017614
 0.72580205 0.27686021 0.56317539 0.5693221 ]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

NO, we Can not create a identity mattrix of shape (3,4). Identity matrix always be a square.

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [20]:
# Solution 1. 

a1 = np.array([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
print(a1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [21]:
# Solution 2. 
matrix = np.linspace(0, 4, 5, dtype=int)

for i in range(4): 
    temp = np.linspace(0, 4, 5, dtype = int)
    matrix = np.vstack((matrix, temp))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])

```


In [48]:
import numpy as np

def distance_vector(a1, point):
    
    result = np.zeros(10)
    i = 0
    
    for p in a1:
        dist = np.sqrt((p[0] - point[0]) ** 2 + (p[1] - point[1]) ** 2)
        # print(dist)
        result[i] = np.round(dist)
        i += 1 
    return result
    

a1 = np.random.random(20) * 100
a1 = np.astype(a1, int).reshape(10, 2)
point = np.array([2,3])

result = distance_vector(a1, point)
print(result)

[96. 76. 56. 53. 93. 98. 77. 84. 62. 66.]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [54]:
a1 = np.arange(336).reshape(6, 7, 8)

# index  --> (1, 5, 3)
print(a1[1, 5, 3])

99


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]

```

In [59]:
def reverse_array(List): 
    a1 = np.array([1, 2, 3, 4, -8, -10], dtype = float)
    return a1[ : : -1]

print(reverse_array([1, 2, 3, 4, -8, -10]))

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



In [62]:
def count_element(array): 

    count = 0
    for i in np.nditer(array): 
        count += 1
    return count

a1 = np.arange(100).reshape(4, 25)
print(count_element(a1))

100


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



In [84]:
def softmax(z): 
    if len(z.shape) > 1:
        return 'Array is not 1D'
    num = np.exp(z) 
    deno = np.sum(np.exp(z))
    # print(num)
    # print(deno)
    return num / deno

z = np.round(np.random.random(10), 2)
# print(z) 
print(softmax(z))

[0.0901313  0.09763808 0.13994753 0.08488247 0.06225679 0.11119301
 0.12790241 0.12536977 0.07233207 0.08834658]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [4]:
def vertical_stack(arr1, arr2):

    if isinstance(arr1, np.ndarray) and isinstance(arr2, np.ndarray): 
        return np.vstack((arr1, arr2))
    else: 
        return 'It is not a numpy array'


arr1 = np.random.randint(1, 100, 10)
arr2 = np.random.randint(1, 100, 10)

print(vertical_stack(arr1, arr2))


[[56 39 97 13 37 36 48 75 55 98]
 [51 77  1  4 69 23 35 26 34 78]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')

```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
 
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')

```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']

```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')

```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
 
```

In [51]:
from datetime import datetime, timedelta

def date_array(date1, date2): 

    if type(date1) != str and type(date2) != str:
        return 'Dates are not of string type.'

    date1 = datetime.strptime(date1, '%Y-%m-%d').date() 
    date2 = datetime.strptime(date2, '%Y-%m-%d').date()

    # print(type(date1))
    # print(type(date2))

    diff = date2 - date1
    current_date = date1
    date_list = []
    for i in range(diff.days):
        date_list.append(str(current_date))
        current_date = current_date + timedelta(days=1)

    return np.array(date_list)

In [50]:
date1 = input('Enter the starting date (yyyy-mm-dd): ')
date2 = input('Enter the Ending date (yyyy-mm-dd): ')

print(date_array(date1, date2))

Enter the starting date (yyyy-mm-dd):  2020-09-15
Enter the Ending date (yyyy-mm-dd):  2020-09-25


2020-09-15
2020-09-25


array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24'], dtype='<U10')

### `Q-14:` Subtract the mean of each row from a matrix.

In [186]:
def subtract_mean(matrix): 
    
    means = np.mean(matrix, axis=1)

    # result = matrix[0] - means[0]
    # for i in range(1, len(matrix)):
    #     result = np.vstack((result, matrix[i] - means[i]))

    result = matrix - means[:, np.newaxis]

    return result


        
matrix = np.arange(20).reshape(4, 5)
print(subtract_mean(matrix))

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [82]:
def swap_column(arr): 
    arr[ : , [1, 0]] = arr[ : , [0, 1]]
    return arr

arr = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8], [5, 6, 7]])
swap_column(arr)

array([[2, 1, 3],
       [5, 4, 6],
       [7, 6, 8],
       [6, 5, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [94]:
def replace_with_minus_one(arr): 
    print(arr % 2 == 1)   
    arr[arr % 2 == 1] = -1
    print(arr)

In [95]:
arr = np.random.randint(1, 100, 20)
print(arr)
replace_with_minus_one(arr)

[98 62 97 70 35 15 72 95 63  4 42 91 52  8 20 32 62  1 23 50]
[False False  True False  True  True False  True  True False False  True
 False False False False False  True  True False]
[98 62 -1 70 -1 -1 72 -1 -1  4 42 -1 52  8 20 32 62 -1 -1 50]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]

``` 

In [99]:
import numpy as np

def max_array(a, b):
    List = []
    for i in range(len(a)):
        List.append(max(a[i], b[i]))

    return np.array(List)

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

print(max_array(a, b))

[6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

```


In [112]:
def normalized_array(arr): 
    print(arr)

arr = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(normalized_array(arr))

[[9546 4421 1362 9511 5325]
 [7680 8016 2558  492 9698]
 [2638 7410 2831 7443 8336]
 [1855 5801 7684 6502 7296]
 [8470 2078 5374 6029  524]
 [4657 1301 9382 5511 1948]
 [6430 6478 2408 3563 6500]
 [4340 1959 1885 3133 7346]]
None


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

```

In [123]:
def kth_largest_elemrnt(arr, n):
    
    arr = np.sort(arr)
    
    i = len(arr) - 1
    while n:
        i -= 1
        n -= 1
    return arr[i + 1]

print('The kth largest element in the array is :', kth_largest_elemrnt(np.array([12,34,40,7,1,0]), 1))

The kth largest element in the array is : 40


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

```

In [139]:
def build_array(arr): 

    repeated = np.repeat(arr, len(arr))
    # print(repeated) 
    
    tiled = np.tile(arr, len(arr))
    # print(tiled)

    return np.concatenate([repeated, tiled])

print(build_array(np.array([1, 2, 3])))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
